name: isla_calc
description: A versatile, modern calculator.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  calc_core:
    path: ./calc_core
  calc_model:
    path: ./calc_model
  calc_tool:
    path: ./calc_tool
  decimal:
  rational:
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  intl: ^0.17.0
  flutter_colorpicker: ^1.0.3
  webview_flutter: ^3.0.2
  url_launcher: ^6.0.20
  flutter_markdown: ^0.6.9+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_generator: 0.2.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Harmony
      fonts:
        - asset: fonts/HarmonyOS_Sans_SC_Regular.ttf
        - asset: fonts/HarmonyOS_Sans_Regular_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans_SC_Thin.ttf
          weight: 100
        - asset: fonts/HarmonyOS_Sans_SC_Light.ttf
          weight: 300
        - asset: fonts/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500
        - asset: fonts/HarmonyOS_Sans_SC_Bold.ttf
          weight: 700
        - asset: fonts/HarmonyOS_Sans_SC_Black.ttf
          weight: 900
    - family: Notoemj
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
          weight: 400
    - family: Seguiemj
      fonts:
        - asset: fonts/seguiemj.ttf
          weight: 400
    - family: Iconfont
      fonts:
        - asset: fonts/iconfont.ttf

  assets:
    - images/logo.png
    - images/icekylin.png
flutter_intl:
  enabled: true
